# Generated by Django 2.2.4 on 2020-07-07 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ok',
            name='ok',
        ),
        migrations.AddField(
            model_name='ok',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.User'),
        ),
    ]
