# Generated by Django 2.2.4 on 2020-07-07 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200707_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityperiod',
            name='empid',
        ),
        migrations.AddField(
            model_name='user',
            name='activity_periods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ActivityPeriod'),
        ),
        migrations.DeleteModel(
            name='first',
        ),
    ]
