# Generated by Django 2.2.4 on 2020-07-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200707_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activity_periods',
        ),
    ]
