# Generated by Django 2.2.4 on 2020-07-07 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_user_activity_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_periods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ActivityPeriod'),
        ),
    ]
