# Generated by Django 2.2.4 on 2020-07-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_activity_periods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
